name: tenant_client_flutter
description: A standalone tenant client app with login and request dashboard.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0

flutter:
  uses-material-design: true
