version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: qhitz-reverse-proxy
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/build:/usr/share/nginx/html:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - qhitz-proxy-network

networks:
  qhitz-proxy-network:
    driver: bridge
